name: Run tests and package firmware
on:
  push:
    branches:
      - '2.8'
  workflow_dispatch:

jobs:
  build:
    name: Run builds
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build firmware inside Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/src -e FLAVOR="tx12;tx12mk2;boxer" ghcr.io/edgetx/edgetx-dev:2.9.0 bash -c "cd /src && ./tools/build-gh.sh"

      - name: Package firmware
        uses: 'actions/upload-artifact@v4'
        with:
          name: edgetx-firmware-custom
          path: |
            *.bin
          retention-days: 15
          if-no-files-found: error
